name: My first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checking out the Code from the repository
          uses: actions/checkout@v4

        - name: List and Read Files
          run: |
              echo "My first Github Actions Job"
              ls -ltra
              cat README.md

        - name: Genearate ASCII Code
          run: cowsay -f penguin "Run for cover, I am cute Penguin" >> penguin.txt
              
        # - name: list Files
        #   run: ls

        # - name: Read Files
        #   run: cat README.md
          