name: Generate ASCII Artwork with cowsay

on:
  push:

jobs:
  ascii_artwork_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -ltra

      - name: Executing a Shell Script
        run:  ./ascii-gen.sh