name: exploring variable and secrets
on: 
    push

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
        - name: Docker Build
          run: docker build -t docker.io/chaiswa/nginx:latest

        - name: Docker Login
          run: docker login --username=chaiswa --password=SwaChay@143

        - name: Docker Publish
          run: docker push docker.io/chaiswa/nginx:latest
    
    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps: 
        - name: Docker Run
          run: docker run -d -p 8080:80 docker.io/chaiswa/nginx:latest
          
